### ISSUE TITLE
自定义字体大小和颜色

### ISSUE THREAD

**Issue by xue-blood** [yihong0618/vscode-gcores#10]
作者您好，感谢您开发和发布这个插件，在使用中，有一点让我觉得不方便的，我的主题是黑色，导致字体颜色和背景对比度太高，看久了会眼花，请问如何自定义字体大小和颜色，谢谢

**Comment by yihong0618** [comment]
@xue-blood 目前暂时不可以，目前字体和颜色会根据你的主题变的，你可以换个主题试试，下个版本我尝试加一下。

**Comment by xue-blood** [comment]
好的，感觉您的回复，我去试一试

**Comment by yihong0618** [comment]
> 好的，感觉您的回复，我去试一试

客气~喜欢就好，好久没维护了，因为用的人可能比较少~
