### ISSUE TITLE
补充几个gapi的参数

### ISSUE THREAD

**Issue by firecloud162** [yihong0618/vscode-gcores#11]
这些是框架调用gpi时候暴露出来的参数。我自己测试过的。
因为要在EXCEL里用脚本做个“历史上的本周”和“I'm Feeling Lucky”听电台的功能，研究了下条件查询参数。

- 排序

**sort**=(_-_)_key_
key可用：
published-at发布时间，comments-count评论数，likes-count赞数，bookmarks-count收藏数，score分值（一个对数公式，具体不明），hits（作用不明）
例：
gapi/v1/radios?sort=published-at    // 按发布时间由旧到新排列
gapi/v1/radios?sort=-likes-count    // 按赞数由高到低排列

- 过滤指定键值

**fields**[_catagory_]=_key1, key2, key3..._
例：
gapi/v1/radios?fields[radios]=title   // 仅显示电台标题
gapi/v1/articles?fields[articles]=title,user    // 仅显示文章标题和作者

- 查询结果

**page**[_limit/offset_]=_number_
limit：返回结果条目数。最大为100。
offset：如果条目超过一页，翻到指定页。
例：
gapi/v1/radios?sort=-score&fields[radios]=title&page[limit]=100

- 指定时间段（似乎是发布时间）

**filter**[_from/to_]=_unit_time_
from：开始时间。
to：结束时间。可以单独使用，不必成对。
例：
gapi/v1/radios?filter[from]=1548547200,000&filter[to]=1548633600,000&fields[radios]=title,user,published-at

**Comment by yihong0618** [comment]
感谢感谢～

**Comment by firecloud162** [comment]
如果用gapi/v1/radios?sort=-comments-count&fields[articles]=title&page[limit]=100这个查询来更新Top100高评论文章，就不用维护静态记录了。
看TLOU2话题和跑团节目评论数上升的势头，等到2077发售，TOP100榜又要有变动了。

**Comment by yihong0618** [comment]
@firecloud162 嗯啊，我之前知道likes能排序，没写在里面，下次我更新下。非常感谢。等我之后把这个项目更新一版，非常感谢你能喜欢。

**Comment by firecloud162** [comment]
我是看到阮一峰的周刊，突然发现：这不是机核发文的大牛吗！:O
:D [鼓掌][鼓掌]

**Comment by firecloud162** [comment]
> @firecloud162 嗯啊，我之前知道likes能排序，没写在里面，下次我更新下。非常感谢。等我之后把这个项目更新一版，非常感谢你能喜欢。

谢谢你！你的项目实在是太酷了！

**Comment by firecloud162** [comment]
刚刚发现Closed issue里有我发过的消息。惭愧！现在还是不会用 :D

**Comment by yihong0618** [comment]
是哈哈。我记得～但当时没用，鉴于我一直没更新，我决定把这几个参数用上啦。感谢感谢

**Comment by firecloud162** [comment]
> 是哈哈。我记得～但当时没用，鉴于我一直没更新，我决定把这几个参数用上啦。感谢感谢

上次我没头没尾地给你发了些“建议”，回想起来，觉得太冒失啦，嘿嘿。这回整理了一下格式。
周末愉快！

**Comment by yihong0618** [comment]
@firecloud162  把这个接口先用在了 gaycore 上了哈哈
https://github.com/yihong0618/gaycore

**Comment by yihong0618** [comment]
@firecloud162 更新啦！感谢。
