### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by SaulTao** [yihong0618/vscode-gcores#19]
when i use this plugin, i got a error: `command 'gcores.refreshExplorer' not found`

**Comment by yihong0618** [comment]
can you provide more info?
like os or vscode version.

**Comment by SaulTao** [comment]
vscode:
```
Version: 1.63.2 (Universal)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 20.3.0
```

> can you provide more info? like os or vscode version.

**Comment by yihong0618** [comment]
Sorry I just test on windows and mac will try to figure out why later

**Comment by SaulTao** [comment]
> Sorry I just test on windows and mac will try to figure out why later

maybe this can help
![image](https://user-images.githubusercontent.com/42377309/148321459-3fbbf350-e4ed-40ad-856f-ddf01cc8a5c0.png)

**Comment by yihong0618** [comment]
Thanks will try

**Comment by yihong0618** [comment]
Seems not support OS: Darwin arm64 20.3.0
Try to fix this later

**Comment by yihong0618** [comment]
@SaulTao 修复了

**Comment by SaulTao** [comment]
谢谢～
