### ISSUE TITLE
缩短Tab Header的标题长度

### ISSUE THREAD

**Issue by rabbitism** [yihong0618/vscode-gcores#5]
![image](https://user-images.githubusercontent.com/14807942/74507158-8e277400-4f36-11ea-8cc4-e83b99e7eb86.png)
这里的长度可以缩短，后面用省略号

**Comment by yihong0618** [comment]
@rabbitism 
好的，我看一下

**Comment by yihong0618** [comment]
@rabbitism 
Fixed, thx.

**Comment by yihong0618** [comment]
@rabbitism 
作者显示不准的问题好像也解决了~
