### ISSUE TITLE
关于TOP100

### ISSUE THREAD

**Issue by firecloud162** [yihong0618/vscode-gcores#6]
除了published-at， sort还有几个可用参数：
comments-count
likes-count
bookmarks-count
score

前三个正好解决TOP100的问题，可以不用缓存json了。

score比较迷，在文章和电台上不明显，在查看评论排序时用处大一些。

**Comment by yihong0618** [comment]
@firecloud162 谢谢，我看一下

**Comment by yihong0618** [comment]
@firecloud162 想了下这块还是不改了。毕竟机核好像没有用这两个参数。不太好我用这个，谢谢你~~~~

**Comment by firecloud162** [comment]
嗯, 我想你是对的. 你回复的评论也有道理, 机核自己没有公开api的用法, 咱们私下交流就好了.
前两天, 可能是因为后台更新的原因, users/USERID/comments突然可以调用了(你可以试试, 如果看不到页面, 应该是权限不足, 可以用自己的USERID), 我还以为这个参数开放权限了.
现在这个参数又恢复限制了.
想想也对, 没看到机核要强化社交属性的意思, 第三方功能做得太激进了, 也不好.

**Comment by yihong0618** [comment]
@firecloud162 嗯啊，谢谢你~
