### ISSUE TITLE
关于收藏文章的图标

### ISSUE THREAD

**Issue by Medesol** [yihong0618/vscode-gcores#7]
目前是没收藏的文章会显示黑色实心书签图标，收藏后图标消失。
建议改成收藏后换成另一个显眼的图标，更能让用户知道我确实收藏过了，而不是插件显示错误

**Comment by yihong0618** [comment]
@Medesol 
好的，我研究一下。谢谢~

**Comment by Medesol** [comment]
感觉最好是未收藏的状态下是空心图标然后已收藏可以是同样形状的实心图标。类似chrome的收藏书签图标那种。

**Comment by yihong0618** [comment]
@Medesol 
好的，这周太忙了，我周末看下，谢谢你。你要是感兴趣可以直接提 pr.
