### ISSUE TITLE
文章配图中的机核水印

### ISSUE THREAD

**Issue by firecloud162** [yihong0618/vscode-gcores#8]
胖五86@gcore提的：
> 发现个亮点，用这个插件看文章，图片的水印都没了 

机核网站上的图片是调用腾讯的oss API处理的。建议能加上这个调用。
image.gcores.com/88ac53db-9cbc-4f66-bb12-3735861c82b7.png?x-oss-process=image/quality,q_90/**watermark,image_d2F0ZXJtYXJrLnBuZw,g_se,x_10,y_10**

**Comment by yihong0618** [comment]
好的。

**Comment by yihong0618** [comment]
@firecloud162 我这周工作比较忙，感兴趣你可以提个pr, 在show.ts里。

**Comment by firecloud162** [comment]
好的。我没用过github，试试看。
